# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f9d7bfe9d38bce6f38508956db7b0b19c6d47a9a1b935285ff35b8af04b275162d86c5490a20ef2a37a0ab71e00a3124aba9090fb3f90663bc565d0db07a8c37

test:
  secret_key_base: 9924452761869ce2153d3793348730644e69087a8ab23552035e1ad3fcb19431aaf16e597118ad12ddb43f3a3ae0823360fc73074d4c73031cf6e0dac2ca01b0

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
